version: "3.1"

services:
  db:
    image: mysql:latest
    expose:
      - "3306"
    ports:
      - "3306:3306"
      - "33060:33060"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sos
    volumes:
      - db-data:/var/lib/mysql
      - ./prisma/init:/docker-entrypoint-initdb.d

volumes:
  db-data:
